CREATE DATABASE MOVIES
GO
USE MOVIES

CREATE TABLE movieInformation(
    MOVIEID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    RELEASEDATE VARCHAR(10) NOT NULL,
    IMAGE VARCHAR(50) NOT NULL,
    NATION VARCHAR(50) NOT NULL,
    LANGUAGE VARCHAR(50) NOT NULL,
    RUNNINGTIME INT NOT NULL,
    DIRECTOR VARCHAR(50) NOT NULL,
    REVIEW VARCHAR(50) NOT NULL
)

CREATE TABLE GENRE(
    GENREID INT,
    GENRE VARCHAR(30) NOT NULL,
)

CREATE TABLE GENRESEARCH(
	MOVIEID INT,
	GENREID INT,
	PRIMARY KEY(MOVIEID,GENREID),
	FOREIGN KEY(MOVIEID) REFERENCES movieInformation(MOVIEID),
	FOREIGN KEY(GENREID) REFERENCES GENRE(GENREID)
);